FROM python:3.11-slim

WORKDIR /airflow

ENV AIRFLOW_HOME=/airflow \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY airflow/requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["airflow", "webserver"]
